### ISSUE TITLE
Problem installing Pixel

### ISSUE THREAD

**Issue by LaurentGatto** [Candihub/pixel#301] opened 2018-11-02 13:21 UTC
I tried installing Pixel but hit the following issue. FYI, I installed docker-compose by fetching it with `curl`, as documented on the docker site, and docker (version 17.05.0-ce, build 89658be) was already installed.

```
$ make bootstrap              
Building web
Step 1/23 : FROM python:3.6
 ---> 3e4c2972dc8d
Step 2/23 : ARG IS_NOT_PRODUCTION
 ---> Using cache
 ---> 0515395b559e
Step 3/23 : ARG BUILD_DATE
 ---> Using cache
 ---> 6c311fc1c06a
Step 4/23 : ARG VCS_REF
 ---> Using cache
 ---> 9ba605eb80b3
Step 5/23 : ARG VERSION
 ---> Using cache
 ---> 74f2ef1aea7c
Step 6/23 : LABEL org.label-schema.build-date $BUILD_DATE org.label-schema.name "Pixel" org.label-schema.description "Integration of smart 'omics' data" org.label-schema.url "https://pixel.candihub.eu/" org.label-schema.vcs-ref $VCS_REF org.label-schema.vcs-url "https://github.com/Candihub/pixel/" org.label-schema.vendor "CandiHub" org.label-schema.version $VERSION org.label-schema.schema-version "1.0"
 ---> Using cache
 ---> 419afba5285e
Step 7/23 : RUN pip install pipenv --upgrade
 ---> Running in 8929a6674268
Collecting pipenv
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a4079898>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pipenv/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a4079390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pipenv/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a4079240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pipenv/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a4079048>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pipenv/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a4079940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pipenv/
  Could not find a version that satisfies the requirement pipenv (from versions: )
No matching distribution found for pipenv
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install pipenv --upgrade' returned a non-zero code: 1
Waiting until database is up
make[1]: Entering directory `/home/lg390/tmp/pixel'
Starting pixel-dev_db_1 ... done
Building web
...
```
When I run what looks like to offending command manually, I don't get any error
```
 % pip install pipenv --upgrade       
Requirement already up-to-date: pipenv in /usr/local/lib/python3.4/dist-packages (2018.10.13)
Requirement already satisfied, skipping upgrade: pip>=9.0.1 in /usr/local/lib/python3.4/dist-packages (from pipenv) (18.1)
Requirement already satisfied, skipping upgrade: virtualenv in /usr/local/lib/python3.4/dist-packages (from pipenv) (16.1.0)
Requirement already satisfied, skipping upgrade: virtualenv-clone>=0.2.5 in /usr/local/lib/python3.4/dist-packages (from pipenv) (0.4.0)
Requirement already satisfied, skipping upgrade: certifi in /usr/local/lib/python3.4/dist-packages (from pipenv) (2018.10.15)
Requirement already satisfied, skipping upgrade: typing; python_version < "3.5" in /usr/local/lib/python3.4/dist-packages (from pipenv) (3.6.6)
Requirement already satisfied, skipping upgrade: setuptools>=36.2.1 in /usr/local/lib/python3.4/dist-packages (from pipenv) (40.5.0)
```
Any help appreciated. Thank you in advance!

**Comment by gaellelelandais** [comment] 2018-11-02 17:06
Hi @LaurentGatto , many thanks for your message. @willdurand an @jmaupetit can you please have a look to this issue ?

**Comment by jmaupetit** [comment] 2018-11-02 17:23
I cannot reproduce your issue. It looks like your Docker daemon has networking issues (DNS errors), and thus cannot install Pipenv during the build. Which operating system are you running?

**Comment by lgatto** [comment] 2018-11-02 19:46
(I opened this issue with the wrong account - following up with my active one)

I on linux, using 
```
$ docker --version
Docker version 17.05.0-ce, build 89658be
$ docker-compose --version
docker-compose version 1.22.0, build f46880fe
```

**Comment by willdurand** [comment] 2018-11-02 20:40
Hi, I have a few questions:

- Which linux OS do you have?
- Do you run Docker inside a VM?
- Can you paste the output of `docker run --rm python:3.6 cat /etc/resolv.conf`?

**Comment by lgatto** [comment] 2018-11-02 21:03
```
$ uname -a
Linux elyacin 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Running docker directly in my OS.
```
% docker run --rm python:3.6 cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1
search home
```
Pinging doesn't work - had to abort if with Ctrl-C:
```
% docker run --rm python:3.6 ping -c 1 google.com
^C ping: google.com: Temporary failure in name resolution
^C 
```

**Comment by willdurand** [comment] 2018-11-02 21:32
It looks like an issue with your Docker setup. The `ping` should work and `python:3.6` is an official Docker image, not a Pixel-specific image. Ubuntu is known for having weird (Docker) connectivity issues like that, likely a `ufw`/`iptables` misconfiguration.

That leads us to some more questions:

- Can you paste the output of `cat /etc/resolv.conf`? (not in Docker)
- Does `ping -c 1 google.com` work? (not in Docker)
- Can you run `docker run --dns 8.8.8.8 --rm python:3.6 ping -c 1 google.com`?

**Comment by lgatto** [comment] 2018-11-03 05:56
Yes, ping works (outside of docker), and 
```
$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1
search home
```
And `docker run --dns 8.8.8.8 --rm python:3.6 ping -c 1 google.com` fails too.

I removed my Ubuntu docker installation and re-installed it using the official docker instructions, as linked on your README file. Here's what I have now, but I still have the same issue.
```
$ docker --version
Docker version 17.03.0-ce, build 3a232c8
lg390@elyacin [06:53:44] [~] 
$ docker-compose --version
docker-compose version 1.22.0, build f46880fe
```

Thank you for your help in sorting this out.

**Comment by pierrepo** [comment] 2018-11-04 16:33
Hi @lgatto 

I might have encountered the same issue as you have right now.

In my lab, Google DNS server (8.8.8.8) is forbidden. I can ping this server but cannot use it as a proper DNS. To be sure, I ran this command: 

```
$ docker run busybox nslookup google.com
nslookup: can't resolve 'google.com'
Server:    8.8.8.8
Address 1: 8.8.8.8
```

If you have a similar error message, first, find the DNS servers used in your lab network:
```
$ nmcli dev show | grep 'IP4.DNS'
IP4.DNS[1]:                             xxx.yyy.zzz.123
IP4.DNS[2]:                             xxx.yyy.zzz.124
```

Then, tell Docker to use them: 
```
$ sudo bash -c 'cat >/etc/docker/daemon.json <<EOF
{                                                                          
    "dns": ["xxx.yyy.zzz.123", "xxx.yyy.zzz.124"]
}
EOF'
```

Finally, restart Docker daemon: 
```
$ sudo service docker restart
```

Then test everything is OK:
```
$ docker run busybox nslookup google.com
Server:    xxx.yyy.zzz.123
Address 1: xxx.yyy.zzz.123 name.yourlab.com

Name:      google.com
Address 1: 2a00:1450:4007:817::200e par10s34-in-x0e.1e100.net
Address 2: 172.217.19.238 par21s11-in-f14.1e100.net
```

Hope this help.

Source: https://stackoverflow.com/questions/24991136/docker-build-could-not-resolve-archive-ubuntu-com-apt-get-fails-to-install-a

**Comment by lgatto** [comment] 2018-11-04 17:15
Thanks @pierrepo for your suggestion. `nslookup` using docker doesn't work

```
$ docker run busybox nslookup google.com
;; connection timed out; no servers could be reached
```

This is on my laptop from home, not being connected on any vpn. I sshed into a computer at work and it works. 

It is clear that my problem is with docker, and outside of the scope of this repo and will close this issue - thank you for your help.

I will move to another machine to test and run Pixel and open another issue if needed.

**Closed** 2018-11-04 17:16 UTC
Labels: question
